docs: created full description
ecomplus/app-opinioes-verificadas pull request #7
Opened 2020-11-19 13:08 UTC by ThaisChaves

2020-11-19 13:10 UTC, ThaisChaves commented
@leomp12 e @talissonf segue a PR com a doc do app para avaliarem.

2020-11-19 18:31 UTC, leomp12 requested changes
Oi @ThaisChaves ,
Acho que a  descrição tá bacana, valeu!
Só as imagens mesmo que ficariam quebradas como estão aqui.

2020-11-19 18:31 UTC, leomp12 commented on functions/public/description.md
> +![exemplo_produto](img/1.png)
Isso aqui não vai funcionar @ThaisChaves 
Vai aparecer no preview aqui no GitHub, mas no Market não, você teria que usar o URL absoluto (completo) mesmo.
Inclusive acho que essas imagens já estão na comunidade, certo? Você pode só copiar o URL de lá ou pode publicar aqui mesmo mas colocar o URL inteiro começando pelo _App base URI_ [aqui](https://github.com/ecomplus/app-opinioes-verificadas/tree/master/assets).

2020-11-19 19:52 UTC, ThaisChaves commented
@leomp12 , corrigi as imagens!

2020-11-20 07:17 UTC, leomp12 approved these changes

2020-11-20 07:18 UTC, leomp12 commented on functions/public/description.md
> + Aplicativo em fase beta, dúvidas/inconsistencias acesse nossa [Comunidade](https://community.e-com.plus/).
```suggestion
 Aplicativo em fase beta, dúvidas/inconsistências acesse nossa [Comunidade](https://community.e-com.plus/).
```

2020-11-20 07:18 UTC, merged